### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by ssokolow** [wejgaard/Holonforth-DOS#2]
Currently, the only things people are certain they're legally allowed to do are the ones you had to agree to as part of the GitHub Terms of Service.

See https://choosealicense.com/no-permission/ for more details.

Would you mind added a `LICENSE` file to the root of the repository containing your preferred license terms?

(The verbatim text of a well-known license is preferable for a variety of reasons, both legal and technical. One being that, if GitHub recognizes the license text, it will add a declaration to the metadata for the repo.

If you choose one of the ones at [https://choosealicense.com/](https://choosealicense.com/), the easiest way is to use their "suggest a license" feature which will create a Pull Request you can just accept.

Otherwise, I'd be happy to try to suggest a well-known license that matches what you want if you describe your intent.

**Comment by wejgaard** [comment]
thanks, done
Wolf Wejgaard

Am Mo., 12. Okt. 2020 um 07:44 Uhr schrieb Stephan Sokolow <
notifications@github.com>:

**Comment by ssokolow** [comment]
...and thank *you*. This looks like a fun thing to play around with on my DOS retrocomputer once I've released the hobby project I'm working on using Open Watcom C/C++ and inline assembly. :)
